package PasswordValiationStrategy;

public enum ErrorCode {
    INVALID_PASSWORD_LENGTH,MISSING_LOWERCASE,MISSING_UPPERCASE
    ,MISSING_UNDERSCORE,MISSING_NUMBER, ILLEGAL_NUMBER_OF_FAILURES_ALLOWED,OK;
}
